### ISSUE TITLE
Annotations of axioms come secondary sources

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/covoc#1]
There is still no solution to the problem that CLO terms should only come from CLO and NCBITAXON terms should only come from NCBI taxon.. As all sources potentially enrich the metadata for each of the terms, maybe it is fine to simply merge everything together (the current state), so if EFO has an annotation on NCBI:001 and ncbitaxon has another, both will be included.

**Comment by paolaroncaglia** [comment]
@matentzn 
@zoependlington 

> There is still no solution to the problem that CLO terms should only come from CLO and NCBITAXON terms should only come from NCBI taxon.. As all sources potentially enrich the metadata for each of the terms, maybe it is fine to simply merge everything together (the current state), so if EFO has an annotation on NCBI:001 and ncbitaxon has another, both will be included.

I'll add a note to the COVOC paper draft to this extent. Can we close this ticket now please, or is there any action item left? Thanks.

**Comment by matentzn** [comment]
If you are happy with the state (I am 85% happy) you can close it! In fact, I will! :)
