### ISSUE TITLE
Review current vocab

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/covoc#10]
I made a simple dump of the key vocab:

https://github.com/EBISPOT/covoc/blob/master/src/ontology/reports/covoc_metadata.csv

Please review. I spotted a few things:

- Colons in covoc_internal_ids (CL template)
- Missing covoc internal ids (could be right, if @paolaroncaglia added intermediate classes)
- Unsplit covoc internal ids
- use of obsolete terms (IDO)

**Comment by matentzn** [comment]
(there may be more things you can spot that I didn't). Ultimately, we need to make sure that all terms from the TSVs are in this table. @zoependlington its possible that some malformed terms dont make it into the release, so you need to check that. If I can help with some hack, let me know.

**Comment by zoependlington** [comment]
Colons in covoc_internal_ids (CL template) have been fixed.

**Comment by paolaroncaglia** [comment]
> I made a simple dump of the key vocab:
> 
> https://github.com/EBISPOT/covoc/blob/master/src/ontology/reports/covoc_metadata.csv
> 
> Please review. I spotted a few things:
> 
>     * Colons in covoc_internal_ids (CL template)
> 
>     * Missing covoc internal ids (could be right, if @paolaroncaglia added intermediate classes)

Some entries were duplicates and didn't need to be referenced back to (because no other info was attached to them), so the submitters agreed to remove them. Hence, some of their internal ids are missing (and should not be added back or used for other terms). Hope that helps! :-) 

> 
>     * Unsplit covoc internal ids
> 
>     * use of obsolete terms (IDO)

**Comment by paolaroncaglia** [comment]
Note for self and @zoependlington : left to address here (if not done already):
- [ ] Unsplit covoc internal ids
- [ ] use of obsolete terms (IDO)

**Comment by paolaroncaglia** [comment]
@zoependlington 
@matentzn 
Not sure if this ticket can be closed now? Thanks.
