### ISSUE TITLE
Keep track of curation stats (Important)

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/covoc#11]
From my conversion with Helen:

We should add a column to all spreadsheets (does not have to be ROBOT template, just leave the second row blank), and keep track of whether we have to request a new term or not; whether the term we chose fit perfectly or kind of fit; I would suggest to, for now, just make an informal comment to that end. This will be an important statistic for the paper later: _How well were relevant concepts covered by existing ontologies before we started?_ How much did we contribute to existing ontologies? This has a variety of interesting sub-questions, like how will are we likely to be set up (ontology-coverage wise) for the next pandemic, and others.

**Comment by zoependlington** [comment]
I've added the column to each sheet at the very end (without anything in the second row so it isn't picked up by ROBOT) so we can fill it in gradually.

**Comment by paolaroncaglia** [comment]
@matentzn @zoependlington 
For the sake of time, I will only fill in the "Curation stats" column if we had to request a new term, or if the mapping isn't exact, or if we needed to have any kind of discussion with the wider community. So no comment will mean that an exact mapping was found in other resources. Any objection please shout :-) Thanks!

**Comment by matentzn** [comment]
Thats perfect I think! Thats exactly what we need!

**Comment by paolaroncaglia** [comment]
Note for self and @zoependlington : this is in progress; I'll leave the ticket open to make sure we remember to fill in the "Curation stats" column where applicable. Also, a reminder to look at the 2 comments columns.

**Comment by paolaroncaglia** [comment]
@zoependlington 
@matentzn 
I think this ticket could be closed now, I referred to it in the paper draft, so we don't forget. Feel free to close please.
