### ISSUE TITLE
Broken annotations

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/covoc#12]
| Term | CID | Broken Field |
| --- | --- | ---|
| NCIT:C49146 | BMV_1 | x-refs |

@paolaroncaglia I moved this xref to the `Paola comment` section because it broke the pipeline.

**Comment by paolaroncaglia** [comment]
> Term 	CID 	Broken Field
> NCIT:C49146 	BMV_1 	x-refs
> 
> @paolaroncaglia I moved this xref to the `Paola comment` section because it broke the pipeline.

You mean this? "Moved from xref-section: [Amino AUMLS:Cid, Peptide, or Protein,ImmunologiUMLS:C FaUMLS:Ctor,PharmaUMLS:CologiUMLS:C SubstanUMLS:Ce]"
That wasn't mine, looks like an error generated while porting Semantic Type UMLSs into comments (which we don't need anyway). I'll delete the comment. Feel free to close. Thanks!

**Comment by paolaroncaglia** [comment]
And, I copied over the right UMLS in the xref field.

**Comment by matentzn** [comment]
Cheers! Closing!
