### ISSUE TITLE
Temporary COVOC ids should get rdfs:label and isa type

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/covoc#4]
While we are tweaking COVOC, I would suggest to add two columns to all spreadsheets:

| COVOC ID | temporary label | superclass |
| ------- | ------- | ------- |
| ID | LABEL | SC % |
| COVOC:001 | temp label 1 | CHEBI:001 |
| COVOC:002 | temp label 2 | MONDO:001 |

For label, just copy the exact stuff we have for the `preferred_covoc_name`. In the superclass column, just make sure to add something that is not a COVID id (something from a reference ontology like MONDO, OBI or CHEBI).

This serves two purposes:

1. COVID terms need temporary labels
2. We need an easy way to do some `glueing`. Right now, we have too many disconnected terms floating around.

@zoependlington can you take care of that? I think you can add both columns to _all_ spreadsheets, even if there are no temporary terms left - the reason for that is that we can use this approach to rapidly add terms in the future.

**Comment by zoependlington** [comment]
Columns have been added to the spreadsheets

**Comment by matentzn** [comment]
Thats great! I think for all COVID ids (only for those!), we can just copy the labels from the `Preferred label` column into the `LABEL` column. Furthermore, I would suggest, by default, to make all terms children of COVID:00000000 id. Check the example on the `BioMed` sheet:

![image](https://user-images.githubusercontent.com/7070631/83160060-61772100-a10f-11ea-9dd6-5c00bbfa7712.png)

In a second round, you can then add some better classifications. Slowly slowly.

@paolaroncaglia @zoependlington other than `COVOC:0000000` we should do as little classification by hand as necessary! This will be an important part of our stats!

**Comment by matentzn** [comment]
Done
