### ISSUE TITLE
Minor problems with covoc annotations

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/covoc#6]
Example 1:

```
[Term]
id: EFO:0000544
name: infection
def: "The state of being infected such as from the introduction of a foreign agent such as serum, vaccine, antigenic substance or organism." []
synonym: "infections" EXACT []
xref: MSH:D007239
xref: OBI:1110021
property_value: http://purl.obolibrary.org/obo/covoc/internal_covoc_id "DIS_37||BMV_77" xsd:string
property_value: IAO:0000117 "James Malone" xsd:string
```
Example 2:

```
[Term]
id: CHEBI:66919
name: ruxolitinib
namespace: chebi_ontology
def: "A pyrazole substituted at position 1 by a 2-cyano-1-cyclopentylethyl group and at position 3 by a pyrrolo[2,3-d]pyrimidin-4-yl group. Used as the phosphate salt for the treatment of patients with intermediate or high-risk myelofibrosis, including primary myelofibrosis, post-polycythemia vera myelofibrosis and post-essential thrombocythemia myelofibrosis." []
comment: Small molecule
subset: 3_STAR
synonym: "(3R)-3-cyclopentyl-3-[4-(7H-pyrrolo[2,3-d]pyrimidin-4-yl)-1H-pyrazol-1-yl]propanenitrile" EXACT IUPAC_NAME [IUPAC]
synonym: "INCB018424" RELATED [ChemIDplus]
synonym: "Jakafi" EXACT []
synonym: "Jakavi" EXACT []
synonym: "ruxolitinib" RELATED INN [KEGG_DRUG]
xref: CAS:941678-49-5 {source="KEGG DRUG"}
xref: CAS:941678-49-5 {source="ChemIDplus"}
xref: DB:08877
xref: Drug_Central:4190 {source="DrugCentral"}
xref: KEGG:D09959
xref: LINCS:LSM-1139
xref: Patent:US2008312258
xref: Patent:US2010190981
xref: PMID:21602517 {source="Europe PMC"}
xref: PMID:21919691 {source="Europe PMC"}
xref: PMID:21926964 {source="Europe PMC"}
xref: PMID:22034658 {source="Europe PMC"}
xref: PMID:22227528 {source="Europe PMC"}
xref: PMID:22279053 {source="Europe PMC"}
xref: PMID:22281165 {source="Europe PMC"}
xref: PMID:22375970 {source="Europe PMC"}
xref: PMID:22375971 {source="Europe PMC"}
xref: PMID:22399854 {source="Europe PMC"}
xref: PMID:22422826 {source="Europe PMC"}
xref: PMID:22474318 {source="Europe PMC"}
xref: PMID:22544377 {source="Europe PMC"}
xref: PMID:22718840 {source="Europe PMC"}
xref: PMID:22830345 {source="Europe PMC"}
xref: Reaxys:18703668 {source="Reaxys"}
xref: Wikipedia:Ruxolitinib
is_a: CHEBI:24431 ! chemical entity
property_value: http://purl.obolibrary.org/obo/chebi/charge "0" xsd:string
property_value: http://purl.obolibrary.org/obo/chebi/formula "C17H18N6" xsd:string
property_value: http://purl.obolibrary.org/obo/chebi/inchi "InChI=1S/C17H18N6/c18-7-5-15(12-3-1-2-4-12)23-10-13(9-22-23)16-14-6-8-19-17(14)21-11-20-16/h6,8-12,15H,1-5H2,(H,19,20,21)/t15-/m1/s1" xsd:string
property_value: http://purl.obolibrary.org/obo/chebi/inchikey "HFNKQEVNSGCOJV-OAHLLOKOSA-N" xsd:string
property_value: http://purl.obolibrary.org/obo/chebi/mass "306.36500" xsd:string
property_value: http://purl.obolibrary.org/obo/chebi/monoisotopicmass "306.15929" xsd:string
property_value: http://purl.obolibrary.org/obo/chebi/smiles "N#CC[C@H](C1CCCC1)n1cc(cn1)-c1ncnc2[nH]ccc12" xsd:string
property_value: http://purl.obolibrary.org/obo/covoc/drug_associated_with_disease "Myelofibrosis||Polycythaemia vera||Graft-versus-host disease||bone marrow cancer" xsd:string
property_value: http://purl.obolibrary.org/obo/covoc/internal_covoc_id "DG_67" xsd:string
property_value: http://purl.obolibrary.org/obo/covoc/preferred_covoc_label "Ruxolitinib" xsd:string
```

As you can see, the SPLIT || is not configured correctly for these (cov:internal_covoc_id, cov:drug_associated_with_disease).

I also believe that we need a better approach for the `cov:internal_covoc_id`. If there can be multiple, shouldn't there be one primary id? @paolaroncaglia My suggestion:

1. `cov:internal_covoc_id` for the 1 main internal id
2. `cov:alt_covoc_id` for the remaining alternative ones.

But its up to you.

**Comment by paolaroncaglia** [comment]
@matentzn 

> I also believe that we need a better approach for the `cov:internal_covoc_id`. If there can be multiple, shouldn't there be one primary id? @paolaroncaglia My suggestion:
> 
>     1. `cov:internal_covoc_id` for the 1 main internal id
> 
>     2. `cov:alt_covoc_id` for the remaining alternative ones.
> 
> 
> But its up to you.

Submitters sometimes entered requests for a same term in two different tabs, or even in the same tab but in separate rows, e.g. one row for singular form of term and another row for plural. In such cases, I "merged", and the decision as to which id is primary is really arbitrary. We could say that the singular form should have primary id and that in duplications across tabs, the primary id should be for the tab that's most relevant (not always applicable though). Going back to that would take time though. They need all ids so they don't lose info wrt their originary vocabulary. How important is it to address this issue before tomorrow's release please? :-)

**Comment by matentzn** [comment]
Thats ok then, really up to you!

@zoependlington Shall we just leave the ID as is then? Not even a split? Leaving:

```
property_value: http://purl.obolibrary.org/obo/covoc/internal_covoc_id "DIS_37||BMV_77" xsd:string
```

Maybe they prefer this, or we can instruct them how to edit the field themselves.

**Comment by matentzn** [comment]
But again, whatever you prefer. No strong feelings here.

**Comment by matentzn** [comment]
(however I would add the SPLIT to the drug-disease thing for sure)

**Comment by zoependlington** [comment]
I already added the split for both, but I can remove it again if we decide we don't want it split for the IDs

**Comment by matentzn** [comment]
Nono, if you did, leave it! Just wanted to avoid work. Its fine! We dont change anything. If the split works, we can close this issue here.
