### ISSUE TITLE
Some terms do not resolve

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/covoc#9]
- [x] HP:0033006
- [x] BAO:0002424
- [x] MONDO:0100120
- [x] PR_P0DTC1
- [x] PR_P0DTD1

We know about the Mondo term - I guess it will appear in the next release.

**Comment by paolaroncaglia** [comment]
>     * [ ]  BAO:0002424

This is http://www.bioassayontology.org/bao#BAO_0002424

> 
>     * [ ]  MONDO:0100120

Yes scheduled for upcoming Mondo release.

> 
>     * [ ]  PR_P0DTC1

Sorry should be PR:P0DTC1-1 

> 
>     * [ ]  PR_P0DTD1

Sorry, should be PR:P0DTD1-1.
The 2 PR entries are from this recent PR work 
https://proconsortium.org/cgi-bin/textsearch_pro?search=search&field0=ALLFLDS&query0=ncbitaxon%3A2697049
Looks like they're not in OLS yet...

Thanks,
Paola
> 
> 
> We know about the Mondo term - I guess it will appear in the next release.

**Comment by matentzn** [comment]
Ok, just make sure you fix them in spreadsheet. 

However, whats wrong with the BAO term I dont know.. I downloaded the latest version of BAO (Feb. 2020) and cant find the term in it.. Can you find out whats up?

**Comment by paolaroncaglia** [comment]
> Ok, just make sure you fix them in spreadsheet (and check the checkboxes here when you did).
> 
> However, whats wrong with the BAO term I dont know.. I downloaded the latest version of BAO (Feb. 2020) and cant find the term in it.. Can you find out whats up?

It is in BioPortal, see
http://bioportal.bioontology.org/ontologies/BAO/?p=classes&conceptid=http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0002424&jump_to_nav=true
No idea what's wrong. What error do you get? Shall we make it a covoc id now, and fix later?

**Comment by matentzn** [comment]
Maybe add covoc ids but make sure you retain the IDs so you can add them as soon as the ontologies had their release.. Same for HP:0033006?

**Comment by paolaroncaglia** [comment]
> Maybe add covoc ids but make sure you retain the IDs so you can add them as soon as the ontologies had their release.. Same for HP:0033006?

Yes, I'll leave @zoependlington to do that please for MONDO:0100120 and HP:0033006. Thanks.
